# Generated by Django 3.2.3 on 2021-05-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('CEP', models.CharField(max_length=200)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemPedido',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='date_added',
            new_name='data_adicionado',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='order',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='product',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='quantity',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='complete',
            new_name='completado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='customer',
            new_name='consumidor',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='date_ordered',
            new_name='data_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='transaction_id',
            new_name='transacao_id',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='digital',
            new_name='fresco',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Pedido',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='enderecoentrega',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente'),
        ),
        migrations.AddField(
            model_name='enderecoentrega',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.pedido'),
        ),
    ]
